### DISCUSSION TITLE
Buildspec.yml for angular build

### DISCUSSION THREAD

**Discussion by vlrm10** [nodesource/distributions#1675] [Q&A]
Hi! I have a question about buildspec, how to write it correctly according updates. I got a script deprecation warning message.
My script look like this
```
version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_16.x | bash -
      - apt-get install -y nodejs
      - echo installing yarn...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt install --no-install-recommends yarn
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli@11.2.6
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --configuration development
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: ***
```
It used a deprecated script for installing nodejs
`curl -sL https://deb.nodesource.com/setup_16.x | bash -`

Could someone help me to rewrite script for installing nodejs using new way
